# Generated by Django 6.1 on 2026-08-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Lasciare vuoto per generarlo dal nome.', max_length=120, unique=True)),
                ('pubblicato', models.BooleanField(default=True, help_text='Se disattivato il contenuto sparisce dal prossimo build del sito.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('sottotitolo', models.CharField(blank=True, max_length=200)),
                ('descrizione', models.TextField(blank=True, help_text='Testo introduttivo. Una riga vuota separa i paragrafi.')),
                ('descrizione_breve', models.CharField(blank=True, help_text='Riga mostrata nella card della home.', max_length=280)),
                ('identita', models.CharField(choices=[('terracotta', 'Terracotta (sagra)'), ('salvia', 'Salvia (Pro Loco, quartiere)'), ('neutro', 'Neutro')], default='salvia', help_text="Colore con cui la realta' compare in tag, pastiglie e dischi.", max_length=12)),
                ('icona', models.CharField(choices=[('tendone', 'Tendone / sagra'), ('chiesa', 'Chiesa'), ('bambini', 'Bambini / Grest'), ('pallone', 'Pallone / sport'), ('casa', 'Casa / circolo'), ('persone', 'Persone / gruppi'), ('musica', 'Musica'), ('cucina', 'Cucina / piatto'), ('calendario', 'Calendario'), ('orologio', 'Orologio'), ('luogo', 'Luogo / mappa'), ('foglia', 'Foglia / natura'), ('fiume', 'Fiume / Sile'), ('stella', 'Stella / festa'), ('regalo', 'Regalo / premi'), ('fuoco', "Fuoco / falo'"), ('libro', 'Libro / racconto'), ('pennello', 'Pennello / laboratori'), ('gioco', 'Gioco'), ('bici', 'Bici / gite')], default='persone', max_length=20)),
                ('tono', models.CharField(choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], default='accent-2-700', help_text="Tinta del disco che porta l'icona nella card della home.", max_length=14)),
                ('sfondo_caldo', models.BooleanField(default=False, help_text='Card su fondo crema («surface») invece del neutro chiaro.')),
                ('collegamento', models.CharField(blank=True, help_text='Pagina interna (es. «/proloco») o indirizzo esterno completo.', max_length=200)),
                ('etichetta_collegamento', models.CharField(blank=True, help_text='Testo della freccia, es. «canizzano.it/proloco».', max_length=80)),
                ('immagine', models.ImageField(blank=True, upload_to='attivita/')),
                ('immagine_alt', models.CharField(blank=True, help_text="Descrizione dell'immagine per screen reader.", max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('ordine', models.PositiveSmallIntegerField(default=0, help_text='Ordine di comparsa in home e nel menu (crescente).')),
                ('in_menu', models.BooleanField(default=False, help_text='Mostra la voce nel menu di navigazione.')),
                ('in_home', models.BooleanField(default=True, help_text='Mostra la card in «Chi tiene in piedi il quartiere».')),
            ],
            options={
                'verbose_name': 'attivita',
                'verbose_name_plural': 'attivita',
                'ordering': ('ordine', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='ImpostazioniSito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostra_banner_sagra', models.BooleanField(default=True, verbose_name='mostra il banner della sagra in home')),
                ('banner_occhiello', models.CharField(blank=True, default='Sta arrivando', max_length=60)),
                ('banner_titolo', models.CharField(blank=True, default='Canizzano in Festa · 2 → 11 ottobre', max_length=160)),
                ('banner_testo', models.CharField(blank=True, max_length=280)),
                ('modalita_sagra', models.BooleanField(default=False, help_text='Da settembre a fine ottobre: /proloco rimanda alla pagina della sagra.', verbose_name="modalita' sagra")),
                ('data_inizio_sagra', models.DateTimeField(blank=True, help_text='Usata dal conto alla rovescia.', null=True)),
                ('mostra_conto_rovescia', models.BooleanField(default=True)),
                ('mostra_sponsor', models.BooleanField(default=True)),
                ('mostra_galleria_proloco', models.BooleanField(default=True)),
                ('iscrizioni_grest_aperte', models.BooleanField(default=True)),
                ('mostra_foto_grest', models.BooleanField(default=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'impostazioni del sito',
                'verbose_name_plural': 'impostazioni del sito',
            },
        ),
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('indirizzo', models.CharField(blank=True, max_length=200)),
                ('mappa_url', models.URLField(blank=True, help_text='Link a Google Maps o OpenStreetMap.')),
            ],
            options={
                'verbose_name': 'luogo',
                'verbose_name_plural': 'luoghi',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Edizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Lasciare vuoto per generarlo dal nome.', max_length=120, unique=True)),
                ('pubblicato', models.BooleanField(default=True, help_text='Se disattivato il contenuto sparisce dal prossimo build del sito.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('anno', models.PositiveSmallIntegerField()),
                ('titolo', models.CharField(blank=True, help_text="Se vuoto viene usato «Nome attivita' + anno».", max_length=160)),
                ('descrizione', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, upload_to='edizioni/')),
                ('immagine_alt', models.CharField(blank=True, max_length=200)),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edizioni', to='eventi.attivita')),
            ],
            options={
                'verbose_name': 'edizione',
                'verbose_name_plural': 'edizioni',
                'ordering': ('-anno', 'attivita__nome'),
                'unique_together': {('attivita', 'anno')},
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raccolta', models.SlugField(help_text='Nome della galleria usata dalla pagina: «proloco», «grest», «storia».', max_length=60)),
                ('immagine', models.ImageField(upload_to='foto/')),
                ('didascalia', models.CharField(blank=True, max_length=200)),
                ('testo_alternativo', models.CharField(blank=True, help_text='Descrizione per screen reader.', max_length=200)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('pubblicato', models.BooleanField(default=True)),
                ('attivita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='eventi.attivita')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'foto',
                'ordering': ('raccolta', 'ordine', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titolo', models.CharField(blank=True, help_text='Se vuoto viene composto dalla data («Venerdì 2 ottobre»).', max_length=120)),
                ('occhiello', models.CharField(blank=True, help_text='La riga sopra il titolo: «si apre il tendone».', max_length=80)),
                ('tono', models.CharField(choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], default='accent', help_text='Tinta della pastiglia con la data.', max_length=14)),
                ('sfondo_chiaro', models.BooleanField(default=False, help_text='Card su fondo neutro chiaro invece che crema.')),
                ('pubblicato', models.BooleanField(default=True)),
                ('edizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='eventi.edizione')),
            ],
            options={
                'verbose_name': 'giornata',
                'verbose_name_plural': 'giornate',
                'ordering': ('data',),
                'unique_together': {('edizione', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Lasciare vuoto per generarlo dal nome.', max_length=120, unique=True)),
                ('pubblicato', models.BooleanField(default=True, help_text='Se disattivato il contenuto sparisce dal prossimo build del sito.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('titolo', models.CharField(max_length=160)),
                ('sommario', models.CharField(blank=True, help_text='Una o due righe, usate nelle card di anteprima.', max_length=280)),
                ('descrizione', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, help_text='Etichetta breve: «Musica», «Cucina», «Bambini»…', max_length=60)),
                ('icona', models.CharField(blank=True, choices=[('tendone', 'Tendone / sagra'), ('chiesa', 'Chiesa'), ('bambini', 'Bambini / Grest'), ('pallone', 'Pallone / sport'), ('casa', 'Casa / circolo'), ('persone', 'Persone / gruppi'), ('musica', 'Musica'), ('cucina', 'Cucina / piatto'), ('calendario', 'Calendario'), ('orologio', 'Orologio'), ('luogo', 'Luogo / mappa'), ('foglia', 'Foglia / natura'), ('fiume', 'Fiume / Sile'), ('stella', 'Stella / festa'), ('regalo', 'Regalo / premi'), ('fuoco', "Fuoco / falo'"), ('libro', 'Libro / racconto'), ('pennello', 'Pennello / laboratori'), ('gioco', 'Gioco'), ('bici', 'Bici / gite')], max_length=20)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('tutto_il_giorno', models.BooleanField(default=False, help_text="Nasconde l'orario nelle date mostrate sul sito.")),
                ('etichetta_data', models.CharField(blank=True, help_text="Come si scrive la data sul sito quando non e' un giorno preciso: «meta' quaresima», «aprile → settembre», «un sabato di maggio». Se vuoto viene composta dalla data qui sopra.", max_length=60)),
                ('tono', models.CharField(blank=True, choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], help_text='Tinta della card nel calendario stagionale. Vuoto = card crema.', max_length=14)),
                ('stagione_scelta', models.CharField(blank=True, choices=[('inverno', 'Inverno'), ('primavera', 'Primavera'), ('estate', 'Estate'), ('autunno', 'Autunno')], help_text="In quale colonna del calendario finisce. Se vuoto viene dedotta dal mese: serve quando la festa sta in un'altra stagione di quella del calendario (il Processo alla Vecchia e' di marzo ma e' d'inverno).", max_length=10, verbose_name='stagione')),
                ('luogo_libero', models.CharField(blank=True, help_text='Sede occasionale, se non presente fra i luoghi.', max_length=160)),
                ('immagine', models.ImageField(blank=True, upload_to='eventi/')),
                ('immagine_alt', models.CharField(blank=True, max_length=200)),
                ('piatto_del_giorno', models.CharField(blank=True, help_text='Il piatto messo in risalto nel programma della sagra.', max_length=160)),
                ('ingresso', models.CharField(blank=True, help_text='Es. «Ingresso libero», «Offerta libera», «5 €».', max_length=120)),
                ('prenotazione_entro', models.DateField(blank=True, help_text='Termine per le prenotazioni, se previste.', null=True)),
                ('link', models.URLField(blank=True, help_text='Locandina, iscrizioni o pagina esterna.')),
                ('link_etichetta', models.CharField(blank=True, default='Scopri di più', max_length=60)),
                ('in_evidenza', models.BooleanField(default=False, help_text='Compare fra i «prossimi appuntamenti» in home.')),
                ('risalto', models.BooleanField(default=False, help_text='Nel programma della sagra diventa un blocco colorato a tutta larghezza.')),
                ('ordine', models.SmallIntegerField(default=0, help_text="A parita' di orario decide chi viene prima.")),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='eventi.attivita')),
                ('edizione', models.ForeignKey(blank=True, help_text="Facoltativo: lega l'evento al programma di un'annata.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='eventi.edizione')),
                ('luogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='eventi.luogo')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventi',
                'ordering': ('inizio', 'ordine', 'titolo'),
                'indexes': [models.Index(fields=['inizio'], name='eventi_even_inizio_0ee7c8_idx'), models.Index(fields=['pubblicato', 'inizio'], name='eventi_even_pubblic_158f06_idx')],
            },
        ),
    ]
