# Generated by Django 6.1 on 2026-08-31 16:47

import django.db.models.deletion
"""
Le pagine di approfondimento degli eventi, l'archivio storico e le foto
ospitate fuori dall'hosting — piu' le icone e i toni nuovi.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='anno',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Anno dello scatto, per le foto d'archivio.", null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='url_esterna',
            field=models.URLField(blank=True, help_text="In alternativa al file: indirizzo diretto dell'immagine su un servizio esterno. Obbligatorio per l'archivio, dove lo spazio sull'hosting non basterebbe."),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='icona',
            field=models.CharField(choices=[('tendone', 'Tendone / sagra'), ('chiesa', 'Chiesa'), ('bambini', 'Bambini / Grest'), ('pallone', 'Pallone / sport'), ('casa', 'Casa / circolo'), ('persone', 'Persone / gruppi'), ('musica', 'Musica'), ('cucina', 'Cucina / piatto'), ('calendario', 'Calendario'), ('orologio', 'Orologio'), ('luogo', 'Luogo / mappa'), ('foglia', 'Foglia / natura'), ('fiume', 'Fiume / Sile'), ('stella', 'Stella / festa'), ('regalo', 'Regalo / premi'), ('fuoco', "Fuoco / falo'"), ('libro', 'Libro / racconto'), ('pennello', 'Pennello / laboratori'), ('gioco', 'Gioco'), ('bici', 'Bici / gite'), ('posate', 'Posate / stand gastronomico'), ('video', 'Video / cinema / proiezione'), ('pimpa', 'Pimpa / il cagnolino a pois'), ('croce', 'Croce cristiana / messa'), ('canneto', 'Canneto / Principato di Canizzano'), ('montagna', 'Montagna / gita fuori porta'), ('fotografia', 'Fotografia / archivio')], default='persone', max_length=20),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='tono',
            field=models.CharField(choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('blu-200', 'Azzurrino chiarissimo'), ('blu-300', 'Azzurrino chiaro'), ('blu-600', 'Azzurro-blu'), ('blu-700', 'Blu scuro'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], default='accent-2-700', help_text="Tinta del disco che porta l'icona nella card della home.", max_length=14),
        ),
        migrations.AlterField(
            model_name='evento',
            name='icona',
            field=models.CharField(blank=True, choices=[('tendone', 'Tendone / sagra'), ('chiesa', 'Chiesa'), ('bambini', 'Bambini / Grest'), ('pallone', 'Pallone / sport'), ('casa', 'Casa / circolo'), ('persone', 'Persone / gruppi'), ('musica', 'Musica'), ('cucina', 'Cucina / piatto'), ('calendario', 'Calendario'), ('orologio', 'Orologio'), ('luogo', 'Luogo / mappa'), ('foglia', 'Foglia / natura'), ('fiume', 'Fiume / Sile'), ('stella', 'Stella / festa'), ('regalo', 'Regalo / premi'), ('fuoco', "Fuoco / falo'"), ('libro', 'Libro / racconto'), ('pennello', 'Pennello / laboratori'), ('gioco', 'Gioco'), ('bici', 'Bici / gite'), ('posate', 'Posate / stand gastronomico'), ('video', 'Video / cinema / proiezione'), ('pimpa', 'Pimpa / il cagnolino a pois'), ('croce', 'Croce cristiana / messa'), ('canneto', 'Canneto / Principato di Canizzano'), ('montagna', 'Montagna / gita fuori porta'), ('fotografia', 'Fotografia / archivio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tono',
            field=models.CharField(blank=True, choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('blu-200', 'Azzurrino chiarissimo'), ('blu-300', 'Azzurrino chiaro'), ('blu-600', 'Azzurro-blu'), ('blu-700', 'Blu scuro'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], help_text='Tinta della card nel calendario stagionale. Vuoto = card crema.', max_length=14),
        ),
        migrations.AlterField(
            model_name='foto',
            name='immagine',
            field=models.ImageField(blank=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='raccolta',
            field=models.SlugField(blank=True, help_text='Nome della galleria usata dalla pagina: «proloco», «grest», «storia».', max_length=60),
        ),
        migrations.AlterField(
            model_name='giornata',
            name='tono',
            field=models.CharField(choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('blu-200', 'Azzurrino chiarissimo'), ('blu-300', 'Azzurrino chiaro'), ('blu-600', 'Azzurro-blu'), ('blu-700', 'Blu scuro'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], default='accent', help_text='Tinta della pastiglia con la data.', max_length=14),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Lasciare vuoto per generarlo dal nome.', max_length=120, unique=True)),
                ('pubblicato', models.BooleanField(default=True, help_text='Se disattivato il contenuto sparisce dal prossimo build del sito.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('titolo', models.CharField(max_length=160)),
                ('anno', models.PositiveSmallIntegerField(blank=True, help_text="L'anno degli scatti, se si conosce.", null=True)),
                ('periodo', models.CharField(blank=True, help_text="Come si scrive l'epoca quando l'anno non e' certo: «anni '70».", max_length=60)),
                ('descrizione', models.TextField(blank=True)),
                ('copertina_url', models.URLField(blank=True, help_text='Immagine di copertina ospitata su un servizio esterno.')),
                ('copertina', models.ImageField(blank=True, upload_to='album/')),
                ('copertina_alt', models.CharField(blank=True, max_length=200)),
                ('album_url', models.URLField(blank=True, help_text="L'album completo sul servizio esterno, se c'e'.")),
                ('ordine', models.SmallIntegerField(default=0, help_text="A parita' di anno decide chi viene prima.")),
                ('attivita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='eventi.attivita')),
            ],
            options={
                'verbose_name': "album d'archivio",
                'verbose_name_plural': "album d'archivio",
                'ordering': ('-anno', 'ordine', 'titolo'),
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(blank=True, help_text="Se valorizzato la foto compare nell'album d'archivio.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='eventi.album'),
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Lasciare vuoto per generarlo dal nome.', max_length=120, unique=True)),
                ('pubblicato', models.BooleanField(default=True, help_text='Se disattivato il contenuto sparisce dal prossimo build del sito.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('occhiello', models.CharField(blank=True, help_text="La riga sopra il titolo: «La proposta d'autunno».", max_length=80)),
                ('titolo', models.CharField(blank=True, help_text="Se vuoto viene usato il titolo dell'evento.", max_length=160)),
                ('sottotitolo', models.CharField(blank=True, help_text='Il sommario in apertura, una o due righe.', max_length=280)),
                ('corpo', models.TextField(blank=True, help_text="Il testo dell'articolo. Riga vuota = nuovo paragrafo; «## » = sottotitolo; «- » = voce di elenco; «> » = nota in evidenza.")),
                ('copertina', models.ImageField(blank=True, upload_to='articoli/')),
                ('copertina_url', models.URLField(blank=True, help_text="In alternativa al file: indirizzo dell'immagine su un servizio esterno. Lo spazio sull'hosting e' poco, meglio i link.")),
                ('copertina_alt', models.CharField(blank=True, max_length=200)),
                ('identita', models.CharField(choices=[('terracotta', 'Terracotta (sagra)'), ('salvia', 'Salvia (Pro Loco, quartiere)'), ('neutro', 'Neutro')], default='salvia', help_text="Colore dell'apertura e dei richiami della pagina.", max_length=12)),
                ('tono', models.CharField(blank=True, choices=[('accent', 'Terracotta piena'), ('accent-200', 'Terracotta chiarissima'), ('accent-300', 'Terracotta chiara'), ('accent-400', 'Terracotta media'), ('accent-2-100', 'Salvia chiarissima'), ('accent-2-500', 'Salvia media'), ('accent-2-600', 'Salvia'), ('accent-2-700', 'Salvia scura'), ('blu-200', 'Azzurrino chiarissimo'), ('blu-300', 'Azzurrino chiaro'), ('blu-600', 'Azzurro-blu'), ('blu-700', 'Blu scuro'), ('neutral-100', 'Neutro chiaro'), ('neutral-700', 'Neutro scuro')], help_text="Tinta della fascia d'apertura. Vuoto = tinta dell'identita'.", max_length=14)),
                ('firma', models.CharField(blank=True, help_text="Chi l'ha scritto: «la Pro Loco», un nome.", max_length=120)),
                ('data_pubblicazione', models.DateField(blank=True, help_text="La data in testa all'articolo. Vuoto = non si mostra.", null=True)),
                ('evento', models.OneToOneField(help_text="L'appuntamento raccontato da questa pagina.", on_delete=django.db.models.deletion.CASCADE, related_name='articolo', to='eventi.evento')),
            ],
            options={
                'verbose_name': 'articolo',
                'verbose_name_plural': 'articoli',
                'ordering': ('-data_pubblicazione', '-creato_il'),
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='articolo',
            field=models.ForeignKey(blank=True, help_text="Se valorizzato la foto compare nella galleria dell'articolo.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='eventi.articolo'),
        ),
        migrations.CreateModel(
            name='DettaglioArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(help_text='«Quando», «Dove», «Quota», «Ritrovo»…', max_length=60)),
                ('valore', models.CharField(max_length=200)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='eventi.articolo')),
            ],
            options={
                'verbose_name': "dettaglio dell'articolo",
                'verbose_name_plural': "dettagli dell'articolo",
                'ordering': ('ordine', 'id'),
            },
        ),
    ]
