# Generated by Django 6.1 on 2026-09-01 11:15

import assistente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiaveAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="A chi la dai: «Claude sul portatile», «l'assistente del telefono»…", max_length=80)),
                ('chiave', models.CharField(default=assistente.models.genera_chiave, editable=False, help_text='Generata dal CMS: si copia, non si sceglie.', max_length=64, unique=True)),
                ('attiva', models.BooleanField(default=True, help_text="Togli la spunta per revocarla: l'agente smette di entrare, subito.")),
                ('sola_lettura', models.BooleanField(default=False, help_text="L'agente può guardare il sito ma non cambiarlo. Utile per provare un assistente nuovo senza rischiare niente.")),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': "chiave dell'assistente",
                'verbose_name_plural': "chiavi dell'assistente",
                'ordering': ('-creata_il',),
            },
        ),
    ]
